import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { LayoutProvider } from "@lyric-app/context/layoutContext";

import Navbar from "@lyric-app/components/navBar/navBar";
import Footer from "@lyric-app/components/footer/footer";
import Sidebar from "@lyric-app/components/sidebar/sidebar";

const InterSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lyric music App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-4 md:p-8 ${InterSans.className} antialiased`}>
        <LayoutProvider>
          <div className="w-full md:flex md:justify-between md:items-start md:space-x-7">
            <div className="transition-all duration-1000">
              <Navbar />
              <div className="py-4 md:py-8">{children}</div>
            </div>
            <Sidebar />
          </div>
        </LayoutProvider>
        <Footer />
      </body>
    </html>
  );
}
